<a href="https://colab.research.google.com/github/oonya/image-processing/blob/master/area_division.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files
uploaded_file = files.upload()

# !ls

Saving a.png to a.png


In [0]:
import numpy as np

a = np.arange(9).reshape((3, 3))
print(a)

yl, xl = np.where(a > 4)
print(xl, yl)

yl.reshape((-1, 1))
xl.reshape((-1, 1))
vec = np.hstack((xl, yl))
print(vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 0 1 2] [1 2 2 2]
[2 0 1 2 1 2 2 2]


In [0]:
import numpy as np
import scipy.spatial as ssp
import cv2
from matplotlib import pyplot as plt


img = cv2.imread("a.png")
bgr_timg = img.copy()
# 二値化
imgray = cv2.cvtColor(bgr_timg, cv2.COLOR_BGR2GRAY)
imgray = cv2.bitwise_not(imgray)
ret,thresh = cv2.threshold(imgray, 0, 255,
            cv2.THRESH_BINARY | cv2.THRESH_OTSU)


# 凸包処理
def convexHull(img):
    bgr_timg = img.copy()

    # 二値化
    imgray = cv2.cvtColor(bgr_timg, cv2.COLOR_BGR2GRAY)
    imgray = cv2.bitwise_not(imgray)
    ret,thresh = cv2.threshold(imgray, 0, 255,
                cv2.THRESH_BINARY | cv2.THRESH_OTSU)
    plt.gray()
    thresh = ~thresh
    plt.imshow(thresh)
    yl, xl = np.where(thresh == 255)

    # 座標データ形式に変換
    yl = yl.reshape((-1, 1))
    xl = xl.reshape((-1, 1))
    vec = np.hstack((xl, yl))

    # 凸包処理
    hull = cv2.convexHull(vec)

    # 結果描画
    result_img = cv2.drawContours(bgr_timg,[hull],
                0,(0,0,255),2)
    
# plt.imshow([convexHull(img)])
# print(convexHull(img))

cv2.convexHull(thresh.reshape(-1, 1))

error: ignored

In [0]:
import numpy as np
import scipy.spatial as ssp
import cv2
from matplotlib import pyplot as plt

img = cv2.imread("a.png")
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(img, 240, 255, cv2.THRESH_BINARY)

contours,hierarchy = cv2.findContours(thresh,  cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

mask = np.zeros_like(thresh)
cv2.drawContours(mask, contours, -1, 0, -1)

convexHull(contours[0])

plt.gray()
# plt.imshow(mask)



error: ignored