<a href="https://colab.research.google.com/github/oonya/image-processing/blob/master/color_categorize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

hsvの範囲を決めてそれより前とか後とかで色を決定する
ユークリッド距離である程度の距離までを決定する
そしたら距離を1.5倍とかにしてもう一回

ユークリッド距離の近いものは赤にする

ある程度遠いものは、決まったものを除いてもう一回
範囲は広くする

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

# 224 218 124
target = np.uint8([[[224, 218, 124]]])# yellow
target = cv2.cvtColor(target, cv2.COLOR_RGB2HSV)

rgb = np.uint8([[[0,255,0], # green
                 [255, 0, 0],# red
                 [0, 0, 255],# blue
                 [0, 0, 0],#   black
                 [255, 255, 0],#  yellow
                 [128, 0, 128],#  purple
                 [255, 165, 0],#  orange
                 [255, 102, 204],# pink
                 [255, 255, 255],# white
                 [205, 133, 63],# brown
                 ]])

colors = ['green', 'red', 'blue', 'black', 'yellow', 'purple', 'orange', 'pink', 'whilte', 'brown']
hsvs = cv2.cvtColor(rgb,cv2.COLOR_RGB2HSV)


min_dist = 1000
target_color = ''

for i, color in enumerate(colors):
  hsv = hsvs[0][i]

  # hの値の上限だけ小さいので重みを高くする
  hsv = [hsv[0]*2, hsv[1], hsv[2]]

  # typeがlistになっているのでnumpyに戻す(np.linalg.normのため)
  hsv = np.array(hsv)

  t = [target[0][0][0]*2, target[0][0][1], target[0][0][1]]
  t = np.array(t)

  dist = np.linalg.norm(t - hsv)
  print('dist of {} is {}'.format(color, dist))
  if min_dist > dist:
    target_color = color
    min_dist = dist

print(target_color)
# print('target', target)


# for i, color in enumerate(colors):
# #   print("{} hsv is {}".format(color, hsvs[0][i]))
#   print("{} : {}".format(color, hsvs[0][i]))

# print(hsv)

dist of green is 209.42301688209918
dist of red is 207.1183236703117
dist of blue is 271.326371737065
dist of black is 170.66927081346543
dist of yellow is 199.44422779313518
dist of purple is 282.1577572919093
dist of orange is 200.214884561563
dist of pink is 301.82445228973745
dist of whilte is 189.77091452590938
dist of brown is 113.69256791892775
brown


In [ ]:
# colorCategorize by CIE LAB

import numpy as np
import cv2
import matplotlib.pyplot as plt



rgb = np.uint8([[[0,255,0], # green
                 [255, 0, 0],# red
                 [0, 0, 255],# blue
                 [0, 0, 0],#   black
                 [255, 255, 0],#  yellow
                 [128, 0, 128],#  purple
                 [255, 165, 0],#  orange
                 [255, 102, 204],# pink
                 [255, 255, 255],# white
                 [205, 133, 63],# brown
                 ]])

labs = cv2.cvtColor(rgb, cv2.COLOR_RGB2Lab)

colors = ['green', 'red', 'blue', 'black', 'yellow', 'purple', 'orange', 'pink', 'whilte', 'brown']

target = np.uint8([[[224, 218, 124]]])# yellow
target = cv2.cvtColor(target, cv2.COLOR_RGB2Lab)


min_dist = 1000
target_color = ''

for i, color in enumerate(colors):
  lab = labs[0][i]
  lab = [lab[0]*0.392156, lab[1]-128, lab[2]-128]
  lab = np.array(lab)

  t = target[0][0]
  t = [t[0]*0.392156, t[1]-128, t[2]-128]# L/255*100 = 0.392156
  t = np.array(t)

  dist = np.linalg.norm(t - lab)
  print('dist of {} is {}'.format(color, dist))
  if min_dist > dist:
    target_color = color
    min_dist = dist

print(target_color)

# for i, color in enumerate(colors):
#   # print("{} lab is {}".format(color, labs[0][i]))
  # print("{} : {}".format(color, labs[0][i]))



print(target)
print(labs)
# print("{} {} {}".format(labs[0],))

dist of green is 83.21565152186456
dist of red is 98.6936371601873
dist of blue is 187.11337631644184
dist of black is 98.51774506820027
dist of yellow is 50.54042245698562
dist of purple is 122.88521728891098
dist of orange is 48.67821362185987
dist of pink is 108.81635097724026
dist of whilte is 50.292216908021224
dist of brown is 39.96547169417942
brown
[[[219 117 175]]]
[[[224  42 211]
  [136 208 195]
  [ 82 207  20]
  [  0 128 128]
  [248 106 223]
  [ 76 187  91]
  [191 152 207]
  [168 197 104]
  [255 128 128]
  [158 149 176]]]


In [ ]:
# colorCategorize by CIE de 2000

import numpy as np
import cv2
import matplotlib.pyplot as plt



rgb = np.uint8([[[0,255,0], # green
                 [255, 0, 0],# red
                 [0, 0, 255],# blue
                 [0, 0, 0],#   black
                 [255, 255, 0],#  yellow
                 [128, 0, 128],#  purple
                 [255, 165, 0],#  orange
                 [255, 102, 204],# pink
                 [255, 255, 255],# white
                 [205, 133, 63],# brown
                 ]])

labs = cv2.cvtColor(rgb, cv2.COLOR_RGB2Lab)

colors = ['green', 'red', 'blue', 'black', 'yellow', 'purple', 'orange', 'pink', 'whilte', 'brown']

target = np.uint8([[[224, 218, 124]]])# yellow
target = cv2.cvtColor(target, cv2.COLOR_RGB2Lab)

# colorsとtargetを本来の範囲に戻す



# min_dist = 1000
# target_color = ''

# # print(target_color)



# for i, color in enumerate(colors):
# #   # print("{} lab is {}".format(color, labs[0][i]))
#   print("{} : {}".format(color, labs[0][i]))

# for i, color in enumerate(colors):
#   print("{} {} {}".format(labs[0][i][0], labs[0][i][1], labs[0][i][2]) + " {} {} {}".format(target[0][0][0], target[0][0][1], target[0][0][2]))

# # print(target)



224 42 211 219 117 175
136 208 195 219 117 175
82 207 20 219 117 175
0 128 128 219 117 175
248 106 223 219 117 175
76 187 91 219 117 175
191 152 207 219 117 175
168 197 104 219 117 175
255 128 128 219 117 175
158 149 176 219 117 175


In [ ]:
# 各色のhsvの範囲

# yellow
hsvLower = np.array([30, 153, 255])    # 抽出する色の下限
hsvUpper = np.array([30, 153, 255])    # 抽出する色の上限

# red
hsv_min = np.array([0,64,0])
hsv_max = np.array([30,255,255])
hsv_min = np.array([150,64,0])
hsv_max = np.array([179,255,255])# 180らへんと0らへんで分ける
hsv_min = np.array([30, 64, 0])
hsv_max = np.array([90,255,255])

# blue
hsv_min = np.array([90, 64, 0])
hsv_max = np.array([150,255,255])


# green


In [ ]:
# 色差計算サイトを使うためのコード群
# url https://plkl.sakura.ne.jp/?page_id=397

import numpy as np
import cv2
import matplotlib.pyplot as plt


colors = ['green', 'red', 'blue', 'black', 'yellow', 'purple', 'orange', 'pink', 'whilte', 'brown']

rgb = np.uint8([[[0,255,0], # green
                 [255, 0, 0],# red
                 [0, 0, 255],# blue
                 [0, 0, 0],#   black
                 [255, 255, 0],#  yellow
                 [128, 0, 128],#  purple
                 [255, 165, 0],#  orange
                 [255, 102, 204],# pink
                 [255, 255, 255],# white
                 [205, 133, 63],# brown
                 ]])

labs = cv2.cvtColor(rgb, cv2.COLOR_RGB2Lab)

target = np.uint8([[[134, 141, 52]]])# red
target = cv2.cvtColor(target, cv2.COLOR_RGB2Lab)
# print(target)
t = target[0][0]
t = [t[0]*0.392156, t[1]-128, t[2]-128]# L/255*100 = 0.392156
correct_target = np.float32(t)

correct_labs = np.zeros_like(labs).astype(np.float32)
for i, color in enumerate(colors):
  lab = labs[0][i]
  lab = [lab[0]*0.392156, lab[1]-128, lab[2]-128]
  correct_labs[0][i] = np.float32(lab)

# for i in range(0, 10):
#   if correct_labs[0][i][1] == labs[0][i][1]-128:
#     print('wrong', i)
#     print(correct_labs[0][i][1], labs[0][i][1]-128)

# print(target)
print(labs)
print(correct_labs)

[[[224  42 211]
  [136 208 195]
  [ 82 207  20]
  [  0 128 128]
  [248 106 223]
  [ 76 187  91]
  [191 152 207]
  [168 197 104]
  [255 128 128]
  [158 149 176]]]
[[[  87.84294   -86.         83.      ]
  [  53.333218   80.         67.      ]
  [  32.15679    79.       -108.      ]
  [   0.          0.          0.      ]
  [  97.254684  -22.         95.      ]
  [  29.803856   59.        -37.      ]
  [  74.901794   24.         79.      ]
  [  65.88221    69.        -24.      ]
  [  99.99978     0.          0.      ]
  [  61.960648   21.         48.      ]]]


In [ ]:
for i, color in enumerate(colors):
  print("{} {} {}".format(correct_labs[0][i][0], correct_labs[0][i][1], correct_labs[0][i][2]) + " {} {} {}".format(correct_target[0], correct_target[1], correct_target[2]))
# print(correct_target)

87.84294128417969 -86.0 83.0 56.470462799072266 -15.0 45.0
53.33321762084961 80.0 67.0 56.470462799072266 -15.0 45.0
32.15679168701172 79.0 -108.0 56.470462799072266 -15.0 45.0
0.0 0.0 0.0 56.470462799072266 -15.0 45.0
97.25468444824219 -22.0 95.0 56.470462799072266 -15.0 45.0
29.803855895996094 59.0 -37.0 56.470462799072266 -15.0 45.0
74.90179443359375 24.0 79.0 56.470462799072266 -15.0 45.0
65.88220977783203 69.0 -24.0 56.470462799072266 -15.0 45.0
99.9997787475586 0.0 0.0 56.470462799072266 -15.0 45.0
61.96064758300781 21.0 48.0 56.470462799072266 -15.0 45.0


In [ ]:
# memo

s = """
87.84294128417969 -86.0 83.0 56.470462799072266 -15.0 45.0 86.42472103685685 31.77720308168713
53.33321762084961 80.0 67.0 56.470462799072266 -15.0 45.0 97.5645545641873 49.489456685549094
32.15679168701172 79.0 -108.0 56.470462799072266 -15.0 45.0 181.20749047140808 78.7080717956268
0.0 0.0 0.0 56.470462799072266 -15.0 45.0 73.74898757773835 48.6530132010607
97.25468444824219 -22.0 95.0 56.470462799072266 -15.0 45.0 64.90264043572203 31.64551818805809
29.803855895996094 59.0 -37.0 56.470462799072266 -15.0 45.0 113.62705630140732 70.80492078219883
74.90179443359375 24.0 79.0 56.470462799072266 -15.0 45.0 54.92462094381455 29.406133133549826
65.88220977783203 69.0 -24.0 56.470462799072266 -15.0 45.0 109.11269853317805 66.31006558537227
99.9997787475586 0.0 0.0 56.470462799072266 -15.0 45.0 64.38013161638571 38.448449180320516
61.96064758300781 21.0 48.0 56.470462799072266 -15.0 45.0 36.539596726862726 25.23365216318493
"""

n = np.uint8([])

s = s.split()
for i in range(7, 80, 8):
  print(s[i])
  n = np.append(n, s[i])

print(colors[np.argmin(n)])

colors = ['green', 'red', 'blue', 'black', 'yellow', 'purple', 'orange', 'pink', 'whilte', 'brown']

31.77720308168713
49.489456685549094
78.7080717956268
48.6530132010607
31.64551818805809
70.80492078219883
29.406133133549826
66.31006558537227
38.448449180320516
25.23365216318493
brown
